version: '3.8'
name: film-gallery

services:
  backend-application-container:
    container_name: backend-application-container
    build:
      context: .
    ports:
      - 8080:8080
  elasticsearch-container:
    image: elasticsearch:8.8.0
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
